### ISSUE TITLE
release/packaging syncinc

### ISSUE THREAD

**Issue by slayoo** [fynv/ThrustRTC#17]
As of today:
- Github releases page (https://github.com/fynv/ThrustRTC/releases) lists 0.3.4 as the latest release
- PyPI (https://pypi.org/project/ThrustRTC/) lists 0.3.13 as the latest release
- Conda-forge (https://anaconda.org/fyplus/thrustrtc/files) lists 0.3.11 as the latest release

It would be great to automate somehow the release process - likely less work for the maintainer, less confusion for users, less issues with outdated packages to handle.

**Comment by fynv** [comment]
I've setup github action workflows for PyPi and Conda.
Conda release version has been updated to 0.3.13.
Since that recent demands are concentrated on the Python binding, I suggest we just forget about the Github release page for now . Those packages invovles Java and C# bindings and is more complicate to build and package.

**Comment by slayoo** [comment]
thank you!
