### ISSUE TITLE
raise an exception in case of incompatible CUDA version

### ISSUE THREAD

**Issue by slayoo** [fynv/ThrustRTC#20]
As detailed in #19, there is a need to raise an error in case of incompatible CUDA hardware/software so that a user knows that there is aneed to upgrade/downgrade CUDA.

The problematic setups are:
A. Volta GPU (or higher) + CUDA 8.0 or lower, where compute_70 hits the upper-bound of CUDA
B. Kepler GPU (or lower) + CUDA 10.2 or higher, where compute_30 hits the lower bound of CUDA

Here's a Python snippet that might help:
https://gist.github.com/f0k/63a664160d016a491b2cbea15913d549

**Comment by fynv** [comment]
Released version 0.3.14. Improved CUDA arch negotiation process.

After the fix, case A won't happen anymore. The highest arch supported by CUDA (instead of the GPU) will be used in that case.

In case B, actual the code is already raising an exception, which is: SystemError("An internal error happend"). After the fix, in addition, the following message will be printed through stdout:

NVRTC version too high for GPU.
CUDA arch negotiation failed.

In case that stdout is not visible, a new method trtc.Get_PTX_Arch() is provided, which can be called after importing ThrustRTC, or after set_libnvrtc_path() when it is needed. A value "-1" will be returned if the CUDA arch negotiation fails.

**Comment by slayoo** [comment]
the above execution through shell was meant to enable stderr messages which are not visible if executing from notebook cell, trying any ThrustRTC code with 0.3.14 gives:
<img width="796" alt="image" src="https://user-images.githubusercontent.com/89685/135479421-cb0ee57c-234a-4754-9b7a-4fa7bf73e792.png">
and there is nothing in the logs besides Jupyter messages about restarting the kernel

**Comment by fynv** [comment]
Sorry that I made a mistake trying to use nvrtcGetNumSupportedArchs() and nvrtcGetSupportedArchs(). And I've just realized that they are not available at all until CUDA 11.2. 
So, version 0.3.14 is definitely broken. Don't use. I'll consider a fix soon.

**Comment by fynv** [comment]
Seems that the only way out is to build a list of "Valid <arch>s" for each CUDA version manually according to the [docment archive](https://developer.nvidia.com/cuda-toolkit-archive). That would take some time..

**Comment by slayoo** [comment]
Would this be helpful?
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/89685/135498784-62071f18-6ed4-4f02-8013-c6a6103c10cc.png">

**Comment by fynv** [comment]
Released version 0.3.15, which should have fixed the bug.
Turns out that CUDA 11.1 doesn't support compute_30 but supports compute_35 and compute_37.
So there should be not need to downgrade CUDA anymore after this fix.

**Comment by slayoo** [comment]
Thank you!
